name: lint text

on: [push]

jobs:
  build:
    name: lint text
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: yarn install --frozen-lockfile
        env:
          HUSKY: 0
      - name: lint text
        run: yarn lint
