name: lint text

on: [push]

jobs:
  build:
    name: lint text
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: yarn install --frozen-lockfile
      - name: lint text
        run: yarn lint
